service: aws-node-express-dynamodb-api-project
frameworkVersion: '3'

custom:
  tableName: 'data-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:us-east-1:241021977882:table/data-table-dev
            # - Fn::GetAtt: [ DataTable, Arn ]
  environment:
    DATA_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: dataId
            AttributeType: S
        KeySchema:
          - AttributeName: dataId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
